import
print('-' * 40)
print(f'{"Mercadinho do Zubiano":^40}')
print(f'{"Lista de Compras":^40}')
print('-' * 40)
n=int(input('Entre com o valor do produto R$'))
aula22a.metade(n)
aula22a.dobro(n)
aula22a.triplo(n)
aula22a.acrescimo(n)
aula22a.desconto(n)